#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 08:26:17 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import book_registration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.resizable(0, 0)
    book_registration_support.set_Tk_var()
    top = Book_Registration (root)
    book_registration_support.init(root, top)
    root.mainloop()

w = None
def create_Book_Registration(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    book_registration_support.set_Tk_var()
    top = Book_Registration (w)
    book_registration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Book_Registration():
    global w
    w.destroy()
    w = None


class Book_Registration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 18 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"
        font11 = "-family {Segoe UI} -size 12 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("600x398+651+252")
        top.title("Book Registration")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.07, rely=0.08, height=47, width=310)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Add new book details''')

        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.07, rely=0.25, relheight=0.66, relwidth=0.86)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=513)

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.18, rely=0.13, height=34, width=43)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Title''')

        self.Label3 = Label(self.Canvas1)
        self.Label3.place(relx=0.15, rely=0.32, height=34, width=71)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Subject''')

        self.Label4 = Label(self.Canvas1)
        self.Label4.place(relx=0.16, rely=0.51, height=34, width=67)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font11)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Author''')

        self.title = Entry(self.Canvas1)
        self.title.place(relx=0.45, rely=0.15,height=24, relwidth=0.48)
        self.title.configure(background="white")
        self.title.configure(disabledforeground="#a3a3a3")
        self.title.configure(font="TkFixedFont")
        self.title.configure(foreground="#000000")
        self.title.configure(highlightbackground="#d9d9d9")
        self.title.configure(highlightcolor="black")
        self.title.configure(insertbackground="black")
        self.title.configure(selectbackground="#c4c4c4")
        self.title.configure(selectforeground="black")
        self.title.configure(textvariable=book_registration_support.btitle)
        self.title.configure(width=244)

        self.subject = Entry(self.Canvas1)
        self.subject.place(relx=0.45, rely=0.34,height=24, relwidth=0.48)
        self.subject.configure(background="white")
        self.subject.configure(disabledforeground="#a3a3a3")
        self.subject.configure(font="TkFixedFont")
        self.subject.configure(foreground="#000000")
        self.subject.configure(highlightbackground="#d9d9d9")
        self.subject.configure(highlightcolor="black")
        self.subject.configure(insertbackground="black")
        self.subject.configure(selectbackground="#c4c4c4")
        self.subject.configure(selectforeground="black")
        self.subject.configure(textvariable=book_registration_support.bsub)
        self.subject.configure(width=244)

        self.author = Entry(self.Canvas1)
        self.author.place(relx=0.45, rely=0.53,height=24, relwidth=0.48)
        self.author.configure(background="white")
        self.author.configure(disabledforeground="#a3a3a3")
        self.author.configure(font="TkFixedFont")
        self.author.configure(foreground="#000000")
        self.author.configure(highlightbackground="#d9d9d9")
        self.author.configure(highlightcolor="black")
        self.author.configure(insertbackground="black")
        self.author.configure(selectbackground="#c4c4c4")
        self.author.configure(selectforeground="black")
        self.author.configure(textvariable=book_registration_support.bauthor)
        self.author.configure(width=244)

        self.backbutton = Button(self.Canvas1)
        self.backbutton.place(relx=0.14, rely=0.76, height=33, width=76)
        self.backbutton.configure(activebackground="#d9d9d9")
        self.backbutton.configure(activeforeground="#000000")
        self.backbutton.configure(background="#d9d9d9")
        self.backbutton.configure(command=book_registration_support.back_Function)
        self.backbutton.configure(disabledforeground="#a3a3a3")
        self.backbutton.configure(foreground="#000000")
        self.backbutton.configure(highlightbackground="#d9d9d9")
        self.backbutton.configure(highlightcolor="black")
        self.backbutton.configure(pady="0")
        self.backbutton.configure(text='''BACK''')

        self.clearbutton = Button(self.Canvas1)
        self.clearbutton.place(relx=0.43, rely=0.76, height=33, width=75)
        self.clearbutton.configure(activebackground="#d9d9d9")
        self.clearbutton.configure(activeforeground="#000000")
        self.clearbutton.configure(background="#d9d9d9")
        self.clearbutton.configure(command=book_registration_support.clear_Function)
        self.clearbutton.configure(disabledforeground="#a3a3a3")
        self.clearbutton.configure(foreground="#000000")
        self.clearbutton.configure(highlightbackground="#d9d9d9")
        self.clearbutton.configure(highlightcolor="black")
        self.clearbutton.configure(pady="0")
        self.clearbutton.configure(text='''CLEAR''')

        self.submitButton = Button(self.Canvas1)
        self.submitButton.place(relx=0.72, rely=0.76, height=33, width=104)
        self.submitButton.configure(activebackground="#d9d9d9")
        self.submitButton.configure(activeforeground="#000000")
        self.submitButton.configure(background="#d9d9d9")
        self.submitButton.configure(command=book_registration_support.submit_Function)
        self.submitButton.configure(disabledforeground="#a3a3a3")
        self.submitButton.configure(font=font9)
        self.submitButton.configure(foreground="#000000")
        self.submitButton.configure(highlightbackground="#d9d9d9")
        self.submitButton.configure(highlightcolor="black")
        self.submitButton.configure(pady="0")
        self.submitButton.configure(text='''ADD BOOK''')
        self.submitButton.configure(width=104)

        self.logoutbutton = Button(top)
        self.logoutbutton.place(relx=0.88, rely=0.03, height=33, width=59)
        self.logoutbutton.configure(activebackground="#d9d9d9")
        self.logoutbutton.configure(activeforeground="#000000")
        self.logoutbutton.configure(background="#d9d9d9")
        self.logoutbutton.configure(command=book_registration_support.logout_Function)
        self.logoutbutton.configure(disabledforeground="#a3a3a3")
        self.logoutbutton.configure(foreground="#000000")
        self.logoutbutton.configure(highlightbackground="#d9d9d9")
        self.logoutbutton.configure(highlightcolor="black")
        self.logoutbutton.configure(pady="0")
        self.logoutbutton.configure(text='''Logout''')






#if __name__ == '__main__':
#    vp_start_gui()



