#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 07:52:40 PM
#    May 18, 2018 07:58:30 PM


import sys
import emp_login_gui
import emp_options
import Db_Operations as dbo
import tkMessageBox as tkmsg

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global bid
    bid = StringVar()



def delete_Function():
    id = bid.get()
    a = dbo.delete_book(id)
    if a == 1:
        tkmsg.showinfo(title="STATUS",message="BOOK DELETED SUCCESSFULLY!")
        destroy_window()
        emp_options.vp_start_gui()
    elif a == 2:
        tkmsg.showerror(title="STATUS",message="BOOK DOESN'T EXIST!")
        destroy_window()
        emp_options.vp_start_gui()
    elif a == 3:
        tkmsg.showerror(title="ERROR", message="BOOK CAN'T BE DELETED!")
        destroy_window()
        emp_options.vp_start_gui()
    sys.stdout.flush()

def back_Function():
    destroy_window()
    emp_options.vp_start_gui()
    sys.stdout.flush()

def logout_Function():
    destroy_window()
    emp_login_gui.vp_start_gui()
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#if __name__ == '__main__':
#    import delete_book
#    delete_book.vp_start_gui()





