#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 10:07:53 AM


import sys
import emp_login_gui
import book_registration
import delete_book
import issue_book
import emp_registration
import emp_search_book
import emp_view_all_book
import return_book

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def add_book_Function():
    destroy_window()
    book_registration.vp_start_gui()
    sys.stdout.flush()

def del_book_Function():
    destroy_window()
    delete_book.vp_start_gui()
    sys.stdout.flush()

def issue_book_Function():
    destroy_window()
    issue_book.vp_start_gui()
    sys.stdout.flush()

def logout_Function():
    destroy_window()
    emp_login_gui.vp_start_gui()
    sys.stdout.flush()

def reg_emp_Function():
    destroy_window()
    emp_registration.vp_start_gui()
    sys.stdout.flush()

def ret_book_Function():
    destroy_window()
    return_book.vp_start_gui()
    sys.stdout.flush()

def search_book_Function():
    destroy_window()
    emp_search_book.vp_start_gui()
    sys.stdout.flush()

def view_all_book_details_Function():
    destroy_window()
    emp_view_all_book.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#if __name__ == '__main__':
#    import emp_options
#    emp_options.vp_start_gui()


