#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 08:18:57 PM


import sys
import emp_login_gui
import emp_options
import Db_Operations as dbo
import tkMessageBox as tkmsg
try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global bid
    bid = StringVar()
    global sroll
    sroll = StringVar()

def back_Function():
    destroy_window()
    emp_options.vp_start_gui()
    sys.stdout.flush()

def clear_Function():
    bid.set("")
    sroll.set("")
    sys.stdout.flush()

def issue_Function():
    id = bid.get()
    roll = sroll.get()
    a = dbo.issue(id,roll)
    if a == 1:
        tkmsg.showinfo(title="GRANTED",message="BOOK ISSUED TO '%s'"%(roll))
        destroy_window()
        emp_options.vp_start_gui()
    elif a == 2:
        tkmsg.showinfo(title="ERROR",message="BOOK DOESN'T EXIST IN LIBRARY!")
        clear_Function()
    elif a == 3:
        tkmsg.showinfo(title="ERROR", message="STUDENT NOT REGISTERED IN LIBRARY!")
        clear_Function()
    elif a == 4:
        tkmsg.showerror(title="ERROR",message="BOOK ALREADY ISSUED!!")
    sys.stdout.flush()

def logout_Function():
    destroy_window()
    emp_login_gui.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#if __name__ == '__main__':
#    import issue_book
#    issue_book.vp_start_gui()


