#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 11:45:05 PM


import sys
import student_login_gui
import tkMessageBox as tkmsg
import Db_Operations as dbo
try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global uname
    uname = StringVar()
    global udepart
    udepart = StringVar()
    global usem
    usem = StringVar()
    global ubatch
    ubatch = StringVar()
    global uroll
    uroll = StringVar()
    global upass
    upass = StringVar()

def back_Function():
    destroy_window()
    student_login_gui.vp_start_gui()
    sys.stdout.flush()

def clear_Function():
    uname.set("")
    udepart.set("")
    usem.set("")
    ubatch.set("")
    uroll.set("")
    upass.set("")
    sys.stdout.flush()

def submit_Function():
    name = uname.get()
    department = udepart.get()
    sem = usem.get()
    batch = ubatch.get()
    roll = uroll.get()
    password = upass.get()
    import re
    pattern1 = "^[a-zA-z0-9!@#$%^&*]{8,}"
    if re.match(pattern1, password):
        a = dbo.stu_registration(name, department, sem, batch, roll, password)
        if a == 1:
            tkmsg.showinfo(title="SUCCESSFUL", message="REGISTRATION DONE SUCCESSFULLY!")
            destroy_window()
            student_login_gui.vp_start_gui()
        elif a == 2:
            tkmsg.showerror(title="ERROR", message="REGISTRATION FAILED!")
            clear_Function()
        elif a == 3:
            tkmsg.showerror(title="ERROR", message="ROLL ID ALREADY EXISTS! PLEASE USE ANOTHER ID!")
            clear_Function()
    else:
        tkmsg.showerror(title="INVALID FORMAT",
                        message="Entered password must contain one alphabet, one non-alphanumeric chracter, one numric character and size of password should not be less than 8")
        clear_Function()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#if __name__ == '__main__':
#    import student_registration
#    student_registration.vp_start_gui()


