#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 19, 2018 12:25:35 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import student_search_book_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.resizable(0, 0)
    student_search_book_support.set_Tk_var()
    top = Search_Book (root)
    student_search_book_support.init(root, top)
    root.mainloop()

w = None
def create_Search_Book(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    student_search_book_support.set_Tk_var()
    top = Search_Book (w)
    student_search_book_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Search_Book():
    global w
    w.destroy()
    w = None


class Search_Book:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 12 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 9 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 18 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"

        top.geometry("600x316+651+256")
        top.title("Search Book")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.07, rely=0.09, height=47, width=178)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Search Book''')

        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.07, rely=0.32, relheight=0.55, relwidth=0.86)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=513)

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.12, rely=0.22, height=34, width=71)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Subject''')

        self.subject = Entry(self.Canvas1)
        self.subject.place(relx=0.41, rely=0.23,height=28, relwidth=0.51)
        self.subject.configure(background="white")
        self.subject.configure(disabledforeground="#a3a3a3")
        self.subject.configure(font="TkFixedFont")
        self.subject.configure(foreground="#000000")
        self.subject.configure(highlightbackground="#d9d9d9")
        self.subject.configure(highlightcolor="black")
        self.subject.configure(insertbackground="black")
        self.subject.configure(selectbackground="#c4c4c4")
        self.subject.configure(selectforeground="black")
        self.subject.configure(textvariable=student_search_book_support.bsub)

        self.backbutton = Button(self.Canvas1)
        self.backbutton.place(relx=0.25, rely=0.58, height=33, width=76)
        self.backbutton.configure(activebackground="#d9d9d9")
        self.backbutton.configure(activeforeground="#000000")
        self.backbutton.configure(background="#d9d9d9")
        self.backbutton.configure(command=student_search_book_support.back_Function)
        self.backbutton.configure(disabledforeground="#a3a3a3")
        self.backbutton.configure(foreground="#000000")
        self.backbutton.configure(highlightbackground="#d9d9d9")
        self.backbutton.configure(highlightcolor="black")
        self.backbutton.configure(pady="0")
        self.backbutton.configure(text='''BACK''')

        self.searchButton = Button(self.Canvas1)
        self.searchButton.place(relx=0.6, rely=0.58, height=33, width=74)
        self.searchButton.configure(activebackground="#d9d9d9")
        self.searchButton.configure(activeforeground="#000000")
        self.searchButton.configure(background="#d9d9d9")
        self.searchButton.configure(command=student_search_book_support.search_Function)
        self.searchButton.configure(disabledforeground="#a3a3a3")
        self.searchButton.configure(font=font11)
        self.searchButton.configure(foreground="#000000")
        self.searchButton.configure(highlightbackground="#d9d9d9")
        self.searchButton.configure(highlightcolor="black")
        self.searchButton.configure(pady="0")
        self.searchButton.configure(text='''SEARCH''')

        self.logoutbutton = Button(top)
        self.logoutbutton.place(relx=0.88, rely=0.03, height=33, width=59)
        self.logoutbutton.configure(activebackground="#d9d9d9")
        self.logoutbutton.configure(activeforeground="#000000")
        self.logoutbutton.configure(background="#d9d9d9")
        self.logoutbutton.configure(command=student_search_book_support.logout_Function)
        self.logoutbutton.configure(disabledforeground="#a3a3a3")
        self.logoutbutton.configure(foreground="#000000")
        self.logoutbutton.configure(highlightbackground="#d9d9d9")
        self.logoutbutton.configure(highlightcolor="black")
        self.logoutbutton.configure(pady="0")
        self.logoutbutton.configure(text='''Logout''')






#if __name__ == '__main__':
#    vp_start_gui()



