#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 19, 2018 12:25:27 AM


import sys
import student_login_gui
import student_options
import student_search_result

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global bsub
    bsub = StringVar()

def back_Function():
    destroy_window()
    student_options.vp_start_gui()
    sys.stdout.flush()

def logout_Function():
    destroy_window()
    student_login_gui.vp_start_gui()
    sys.stdout.flush()

def search_Function():
    sub = bsub.get()
    destroy_window()
    student_search_result.vp_start_gui(sub)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#if __name__ == '__main__':
#    import student_search_book
#    student_search_book.vp_start_gui()


